AMENITIES = [
    "Air Conditioning",
    "Swimming Pool",
    "Gym/Fitness Center",
    "Parking Space",
    "24/7 Security",
    "Wi-Fi",
    "Cable TV",
    "Laundry Facilities",
    "Elevator",
    "Furnished",
    "Unfurnished",
    "Pet Friendly",
    "Balcony/Patio",
    "Garden/Yard",
    "Housekeeping",
    "Concierge",
    "Business Center",
    "Playground",
    "BBQ Area",
    "Tennis Court",
    "Spa/Sauna",
    "On-site Maintenance",
    "Wheelchair Access",
    "Generator Backup",
    "Solar Water Heating",
    "Smart Home Features",
    "Walk-in Closets",
    "Central Heating",
    "Fireplace",
    "Beach Access"
]

LOCATIONS = [
    # Trinidad
    "Port of Spain",
    "San Fernando",
    "Chaguanas",
    "Arima",
    "Marabella",
    "Couva",
    "Point Fortin",
    "Tunapuna",
    "Scarborough (Tobago)",
    "Diego Martin",
    "Sangre Grande",
    "Princes Town",
    "Rio Claro",
    "Debe",
    "Penal",
    "Siparia",
    "Arouca",
    "St. Augustine",
    "Curepe",
    "St. James",
    "Valsayn",
    "Westmoorings",
    "Goodwood Park",
    "Glencoe",
    "Santa Cruz",
    
    # Tobago
    "Crown Point",
    "Buccoo",
    "Plymouth",
    "Black Rock",
    "Lowlands",
    "Mount Irvine",
    "Belle Garden",
    "Roxborough",
    "Charlotteville",
    "Speyside"
]