LANDLORDS_DATA = [
            ('bob', 'bob@bobmail.com', 'bobpass'),
            ('alice', 'alice@alice.com', 'alicepass'),
            ('charlie', 'charlie@charlie.com', 'charliepass')
        ]

APARTMENTS_DATA = [
    ('SpaceSide Villas', 'Spacious 1-Bedroom Apartment, Cozy and modern apartment with all amenities.', 1200.00),
    ('Family Heights', '2-Bedroom Family Apartment, Perfect for a small family with ample space.', 1500.00),
    ('Urban Retreat', 'Cozy Studio, Compact and perfect for one person.', 800.00),
    ('Luxury Towers', 'Luxury 3-Bedroom Apartment, Spacious with top-of-the-line finishes.', 2200.00),
    ('City View Apartments', 'Compact 1-Bedroom Apartment, Perfect for city living.', 1000.00),
    ('Grand Residence', 'Large 2-Bedroom Apartment, Spacious with modern amenities.', 1700.00),
    ('Suburban Estates', 'Suburban 3-Bedroom Apartment, Great for families looking for suburban comfort.', 1800.00),
    ('Loft Heights', 'Charming 1-Bedroom Loft, Charming loft for urban living.', 1100.00),
    ('Affordable Living', 'Affordable Studio Apartment, Budget-friendly apartment with essential amenities.', 600.00),
    ('Executive Suites', 'Executive 2-Bedroom Apartment, High-end apartment for professionals.', 2000.00),
    ('Mountain View Residences', '2-Bedroom Mountain View Apartment, Scenic views with modern amenities.', 1900.00),
    ('Lakeside Retreat', 'Luxury 1-Bedroom Apartment, Beautiful lakeside views in a tranquil setting.', 2100.00),
    ('Downtown Lofts', 'Modern 2-Bedroom Loft, In the heart of the city with a spacious open floor plan.', 1600.00),
    ('Sunset Tower', 'Spacious 3-Bedroom Apartment, Stunning sunset views with balcony.', 2300.00),
    ('Parkside Heights', 'Cozy 1-Bedroom Apartment, Quiet park-facing apartment with natural light.', 850.00),
    ('Riverfront Flats', '2-Bedroom Riverfront Apartment, Views of the river and modern amenities.', 1750.00),
    ('Coastal Breeze Apartments', '3-Bedroom Beachfront Apartment, Relaxing seaside living.', 2500.00),
    ('Hilltop Residences', '3-Bedroom Hilltop Apartment, Secluded, spacious living with panoramic views.', 2400.00),
    ('City Edge Apartments', '2-Bedroom Apartment, Modern design with easy access to downtown.', 1400.00),
    ('Shoreline Apartments', '1-Bedroom Coastal Apartment, Located by the water with scenic views.', 950.00),
    ('Woodland Apartments', '2-Bedroom Woodland Apartment, Nestled in nature with a cozy feel.', 1300.00),
    ('Skyline Towers', 'Luxury 4-Bedroom Penthouse, Top floor apartment with breathtaking views.', 3500.00),
    ('The Grove', '3-Bedroom Garden Apartment, Surrounded by greenery and quiet living.', 2100.00),
    ('Uptown Flats', '2-Bedroom Urban Apartment, Located in the center of a vibrant city area.', 1600.00),
    ('Mountain Ridge Apartments', 'Studio Apartment, Cozy studio with mountain views.', 900.00),
    ('Riverside Court', '2-Bedroom Riverside Apartment, Peaceful living by the river with ample space.', 1800.00),
    ('The Courtyard', '1-Bedroom Courtyard Apartment, Quaint apartment with views of the private courtyard.', 1050.00),
    ('Parkview Towers', '2-Bedroom Apartment, Located in a quiet park area with fantastic views.', 1700.00),
    ('Seaside Villas', 'Luxury 1-Bedroom Apartment, Beautiful seaside views with premium finishes.', 2100.00),
    ('Brickstone Apartments', '3-Bedroom Loft, Trendy loft-style living in a brick building.', 1900.00),
    ('Sunset Ridge', '1-Bedroom Sunset View Apartment, Quiet and private with incredible sunset views.', 1100.00),
    ('Crystal Bay Apartments', '2-Bedroom Beach Apartment, Living by the bay with breathtaking views.', 1850.00),
    ('Central Park Lofts', 'Luxury 2-Bedroom Loft, High-end apartment near the city’s central park.', 2500.00),
    ('Silverstone Residences', '4-Bedroom Family Home, Spacious family apartment with a large backyard.', 2700.00),
    ('The Atrium', '2-Bedroom High-Rise Apartment, Bright and airy with modern finishes.', 1600.00),
    ('Vista Park Apartments', 'Studio Park View Apartment, Cozy studio in a serene park environment.', 950.00),
    ('Pinehill Manor', 'Luxury 3-Bedroom Apartment, Located in a high-end neighborhood with stunning views.', 2300.00),
    ('Marina Bay Apartments', '1-Bedroom Marina Apartment, Located by the marina with lovely sea views.', 1250.00),
    ('Garden View Villas', '3-Bedroom Villa, Surrounded by lush gardens in a tranquil area.', 2000.00),
    ('Oceanfront Towers', 'Luxury 2-Bedroom Oceanfront Apartment, Views of the ocean with upscale features.', 2400.00),
    ('Valley Springs', '2-Bedroom Suburban Apartment, A peaceful apartment located in the suburbs.', 1400.00),
    ('Lakefront Retreat', 'Luxury 4-Bedroom Apartment, Spacious apartment with a lakefront view.', 3000.00),
    ('Vista Del Mar', '3-Bedroom Coastal Apartment, Close to the beach with wide views of the ocean.', 2200.00),
    ('Glenwood Heights', '2-Bedroom Hillside Apartment, Tranquil living in the hills with nature views.', 1600.00),
    ('Harmony Gardens', '1-Bedroom Garden Apartment, Cozy unit with a garden view.', 850.00),
    ('The Estate', 'Luxury 5-Bedroom Villa, Huge mansion with luxurious interiors.', 5000.00),
    ('Kingsley Towers', 'Studio High-Rise Apartment, Trendy living in a modern high-rise.', 1000.00),
    ('Diamond Residences', '2-Bedroom Penthouse, Exclusive penthouse with city views.', 3000.00),
    ('The Oakwood', '2-Bedroom Woodland Retreat, Cozy apartment surrounded by oak trees.', 1400.00),
    ('Sunridge Apartments', '1-Bedroom Modern Apartment, Bright apartment in a sunny location.', 950.00),
    ('The Summit', 'Luxury 3-Bedroom Mountain Apartment, Luxurious living with amazing mountain views.', 2600.00),
    ('Prairie Ridge', 'Studio Apartment, Quiet and private with a view of the prairie.', 800.00),
    ('Northfield Apartments', '3-Bedroom Family Apartment, Spacious home perfect for families.', 1700.00),
    ('City Lights Apartments', '1-Bedroom High-Rise Apartment, Located in the heart of the city with city lights view.', 1300.00),
    ('The Ivy', '2-Bedroom Garden Apartment, Quiet apartment in a lovely garden setting.', 1500.00),
    ('Woodland Edge', '3-Bedroom Suburban Apartment, Perfect for a growing family in a peaceful area.', 1900.00),
    ('Westport Residences', '2-Bedroom Apartment, Centrally located with all the essentials.', 1200.00),
    ('Horizon Heights', '1-Bedroom Apartment, Modern apartment with panoramic city views.', 1150.00),
    ('Violet Gardens', '2-Bedroom Garden Apartment, Peaceful and green, ideal for nature lovers.', 1350.00),
    ('Redwood Towers', '3-Bedroom Apartment, Large space with modern amenities and stunning views.', 2100.00),
    ('Eagle Nest Apartments', '1-Bedroom Loft, Spacious loft with a unique design.', 1200.00),
    ('Lakeshore Residences', 'Luxury 4-Bedroom Lakeside Home, Stunning views and luxurious interiors.', 3500.00),
    ('Bayview Villas', '2-Bedroom Oceanfront Apartment, Cozy and modern with a view of the bay.', 1900.00),
    ('Pinecrest Apartments', '2-Bedroom Hillside Apartment, Tranquil apartment with forest views.', 1600.00),
    ('Golden Peaks', '3-Bedroom Mountain Cabin, Retreat-like living with mountain views.', 2200.00),
    ('Maplewood Residences', '2-Bedroom Suburban Apartment, Quiet and comfortable living.', 1300.00),
    ('Crystal Springs', '3-Bedroom Penthouse, High-end living in a luxurious penthouse suite.', 2800.00),
    ('Riverstone Apartments', '1-Bedroom River View Apartment, Perfect for nature lovers with river views.', 1150.00),
    ('The Maple Grove', '2-Bedroom Garden Apartment, Located in a scenic grove surrounded by trees.', 1500.00),
    ('Cedar Ridge', 'Luxury 4-Bedroom House, Beautiful home with modern amenities and views.', 4000.00),
    ('The Plaza', 'Studio Apartment, Affordable and cozy studio in the city center.', 900.00),
    ('Starlight Apartments', '1-Bedroom Penthouse, Elegant apartment with city views and modern finishes.', 1400.00),
    ('Blue Ridge Apartments', '3-Bedroom Family Apartment, Spacious apartment with a peaceful neighborhood.', 2000.00),
    ('Sunrise Residences', '2-Bedroom City Apartment, Located in the bustling heart of the city.', 1600.00),
    ('Clearwater Heights', '2-Bedroom Apartment, Perfect for small families looking for quiet living.', 1450.00),
    ('The Cove', '1-Bedroom Coastal Apartment, Relaxing coastal living with panoramic ocean views.', 1050.00),
    ('Seabreeze Towers', '3-Bedroom Ocean View Apartment, Stunning ocean views with plenty of space.', 2200.00),
    ('Majestic Estates', 'Luxury 5-Bedroom Mansion, Spacious and luxurious living with a large backyard.', 4500.00),
    ('Bluewater Apartments', '2-Bedroom Beach Apartment, Oceanfront apartment with great amenities.', 1800.00),
    ('Elysian Heights', '2-Bedroom Penthouse, Top-floor apartment with incredible views of the skyline.', 2700.00)
]


REVIEWS_DATA = [
    ("Great place to live! I really enjoyed my time here.", 5),
    ("The apartment was good, but it didn't fully meet my expectations.", 3),
    ("I had a wonderful experience! Everything was just right.", 5),
    ("Decent apartment, but I ran into a few problems during my stay.", 3),
    ("Had a great time living here. Would recommend it to others.", 5),
    ("The apartment was fine, but I wouldn't say it was exceptional.", 3),
    ("Wonderful place! I loved the neighborhood and the vibe of the apartment.", 5),
    ("Good apartment overall, but I encountered a couple of issues during my stay.", 3),
    ("Really enjoyed the experience. The apartment was just right for me.", 5),
    ("Nice apartment, but it wasn’t exactly what I was looking for.", 4),
    ("The apartment was lovely, but I had some issues with the building.", 2),
    ("Amazing stay! The apartment and surroundings were perfect.", 5),
    ("I enjoyed living here, but I think the rent could be a little more reasonable.", 4),
    ("I had a pleasant experience. The apartment was nice and in a good location.", 4),
    ("The location was perfect, but the apartment didn't meet all my needs.", 3),
    ("Great experience! The apartment was exactly what I needed.", 5),
    ("Good apartment, but the overall experience wasn’t as smooth as expected.", 3),
    ("I absolutely loved it here! It was a great apartment for me.", 5),
    ("I was happy with the apartment, but there were a couple of small things I didn't like.", 4),
    ("Nice apartment with a good atmosphere. Would stay here again.", 5),
    ("It was an okay experience. The apartment was fine, but I expected more.", 3),
    ("Perfect for what I needed. I had a great time living here.", 5),
    ("I really liked it here, but there were a few things that could be improved.", 3),
    ("Nice apartment, but I had a bit of trouble with the overall experience.", 3),
    ("I had a great stay, but the management could have been more responsive.", 2),
    ("Great location, but the apartment didn’t live up to my expectations.", 3),
    ("Not a terrible place to stay, but I had issues with the maintenance team.", 2),
    ("Nice apartment, but a bit small for the price.", 3),
    ("I loved my stay, but I ran into issues with the heating system.", 2),
    ("Decent apartment, but there were too many noisy neighbors.", 2),
    ("The apartment was good, but it wasn't as clean as I hoped.", 2),
    ("I had an okay time, but the building itself seemed outdated.", 3),
    ("Great place to stay! I would definitely recommend it to others.", 5),
    ("The apartment was fine, but I expected a bit more for the price.", 3),
    ("Good location, but the apartment wasn’t as modern as I hoped.", 3),
    ("I enjoyed my stay, but I had some issues with the overall living experience.", 3),
    ("I loved the apartment! It had everything I needed and was in a great location.", 5),
    ("The apartment was good, but I had trouble with the building management team.", 2),
    ("Nice place, but I found a few things that could be better.", 3),
    ("Great apartment, but there were a few things I didn’t love about it.", 4),
    ("Really nice apartment, but the location wasn't ideal for me.", 3),
    ("Overall, a great experience. The apartment was nice and in a good spot.", 4),
    ("The apartment was decent, but there were some things that didn’t work well for me.", 3),
    ("Loved the apartment, but there were a few small issues I ran into during my stay.", 4),
    ("Great place to live. The apartment was in great condition and I enjoyed my stay.", 5),
    ("Good apartment, but there were a few maintenance issues that needed to be addressed.", 3),
    ("I had an overall great stay, but there were a couple of minor inconveniences.", 4),
    ("The apartment was decent, but I wish there was more space.", 3),
    ("Perfect place to stay for a short-term rental.", 5),
    ("Nice apartment, but there were a few things I didn’t like about the management.", 3),
    ("The apartment was great for me. I really enjoyed the space and the location.", 5),
    ("I regret staying here. The apartment was nothing like the pictures.", 1),
    ("The worst experience I’ve had with an apartment. I wouldn’t recommend it to anyone.", 1),
    ("Very disappointed. The apartment was not clean and maintenance was unresponsive.", 1),
    ("Extremely noisy, couldn't sleep well. Not worth the price at all.", 1),
    ("Had to deal with constant plumbing issues. Very frustrating.", 1)
]


TENANTS_DATA = [
    ('john_doe', 'john.doe@john_doe.com', 'johnpass'),
    ('jane_doe', 'jane.doe@jane_doe.com', 'janepass'),
    ('mike_roe', 'mike.roe@mike_roe.com', 'mikepass'),
    ('lucy_smith', 'lucy.smith@lucy_smith.com', 'lucypass'),
    ('sam_wilson', 'sam.wilson@sam_wilson.com', 'sampass'),
    ('lily_brown', 'lily.brown@lily_brown.com', 'lilypass'),
    ('mark_taylor', 'mark.taylor@mark_taylor.com', 'markpass'),
    ('anna_jones', 'anna.jones@anna_jones.com', 'annapass'),
    ('jack_white', 'jack.white@jack_white.com', 'jackpass'),
    ('emily_black', 'emily.black@emily_black.com', 'emilypass'),
    ('oliver_harris', 'oliver.harris@oliver_harris.com', 'oliverpass'),
    ('sofia_davis', 'sofia.davis@sofia_davis.com', 'sofiapass'),
    ('liam_martin', 'liam.martin@liam_martin.com', 'liampass'),
    ('ava_rodriguez', 'ava.rodriguez@ava_rodriguez.com', 'avapass'),
    ('elijah_lee', 'elijah.lee@elijah_lee.com', 'elijahpass'),
    ('chloe_garcia', 'chloe.garcia@chloe_garcia.com', 'chloepass'),
    ('mason_white', 'mason.white@mason_white.com', 'masonpass'),
    ('mia_moore', 'mia.moore@mia_moore.com', 'miapass'),
    ('noah_smith', 'noah.smith@noah_smith.com', 'noahpass'),
    ('lucas_williams', 'lucas.williams@lucas_williams.com', 'lucaspass'),
    ('isabella_johnson', 'isabella.johnson@isabella_johnson.com', 'isabellapass'),
    ('aiden_smith', 'aiden.smith@aiden_smith.com', 'aidenpass'),
    ('sophia_brown', 'sophia.brown@sophia_brown.com', 'sophiapass'),
    ('jackson_miller', 'jackson.miller@jackson_miller.com', 'jacksonpass'),
    ('ella_lee', 'ella.lee@ella_lee.com', 'ellapass'),
    ('benjamin_martin', 'benjamin.martin@benjamin_martin.com', 'benjaminpass'),
    ('charlotte_clark', 'charlotte.clark@charlotte_clark.com', 'charlottepass'),
    ('michael_harris', 'michael.harris@michael_harris.com', 'michaelpass'),
    ('madison_wilson', 'madison.wilson@madison_wilson.com', 'madisonpass'),
    ('joseph_smith', 'joseph.smith@joseph_smith.com', 'josephpass'),
    ('grace_smith', 'grace.smith@grace_smith.com', 'gracepass'),
    ('daniel_morris', 'daniel.morris@daniel_morris.com', 'danielpass'),
    ('hannah_miller', 'hannah.miller@hannah_miller.com', 'hannahpass'),
    ('evelyn_taylor', 'evelyn.taylor@evelyn_taylor.com', 'evelynpass'),
    ('henry_james', 'henry.james@henry_james.com', 'henrypass'),
    ('bella_scott', 'bella.scott@bella_scott.com', 'bellapass'),
    ('william_wilson', 'william.wilson@william_wilson.com', 'williampass'),
    ('lucas_jones', 'lucas.jones@lucas_jones.com', 'lucaspass'),
    ('scarlett_hall', 'scarlett.hall@scarlett_hall.com', 'scarlettpass'),
    ('david_martin', 'david.martin@david_martin.com', 'davidpass'),
    ('caroline_davis', 'caroline.davis@caroline_davis.com', 'carolinepass'),
    ('victoria_smith', 'victoria.smith@victoria_smith.com', 'victoriapass'),
    ('james_white', 'james.white@james_white.com', 'jamespass'),
    ('madeline_wilson', 'madeline.wilson@madeline_wilson.com', 'madelinepass'),
    ('gabriel_brown', 'gabriel.brown@gabriel_brown.com', 'gabrielpass'),
    ('harper_taylor', 'harper.taylor@harper_taylor.com', 'harperpass'),
    ('elizabeth_miller', 'elizabeth.miller@elizabeth_miller.com', 'elizabethpass'),
    ('charlie_harris', 'charlie.harris@charlie_harris.com', 'charliepass'),
    ('michael_taylor', 'michael.taylor@michael_taylor.com', 'michaelpass'),
    ('amelia_jones', 'amelia.jones@amelia_jones.com', 'ameliapass'),
    ('jackson_johnson', 'jackson.johnson@jackson_johnson.com', 'jacksonpass'),
    ('ariana_smith', 'ariana.smith@ariana_smith.com', 'arianapass'),
    ('grace_jackson', 'grace.jackson@grace_jackson.com', 'gracepass'),
    ('madison_smith', 'madison.smith@madison_smith.com', 'madisonpass'),
    ('joseph_moore', 'joseph.moore@joseph_moore.com', 'josephpass'),
    ('sophia_martin', 'sophia.martin@sophia_martin.com', 'sophiapass'),
    ('elijah_jones', 'elijah.jones@elijah_jones.com', 'elijahpass'),
    ('sebastian_wilson', 'sebastian.wilson@sebastian_wilson.com', 'sebastianpass'),
    ('lucas_hill', 'lucas.hill@lucas_hill.com', 'lucaspass'),
    ('olivia_martin', 'olivia.martin@olivia_martin.com', 'oliviapass'),
    ('victor_brown', 'victor.brown@victor_brown.com', 'victorpass'),
    ('rebecca_scott', 'rebecca.scott@rebecca_scott.com', 'rebeccapass'),
    ('henry_wilson', 'henry.wilson@henry_wilson.com', 'henrypass'),
    ('daniel_jones', 'daniel.jones@daniel_jones.com', 'danielpass'),
    ('ella_james', 'ella.james@ella_james.com', 'ellapass'),
    ('isabella_moore', 'isabella.moore@isabella_moore.com', 'isabellapass'),
    ('oscar_harris', 'oscar.harris@oscar_harris.com', 'oscarpass'),
    ('lucas_taylor', 'lucas.taylor@lucas_taylor.com', 'lucaspass'),
    ('natalie_white', 'natalie.white@natalie_white.com', 'nataliepass'),
    ('samantha_brown', 'samantha.brown@samantha_brown.com', 'samanthapass'),
    ('jonathan_lee', 'jonathan.lee@jonathan_lee.com', 'jonathanpass'),
    ('lily_jones', 'lily.jones@lily_jones.com', 'lilypass'),
    ('ella_white', 'ella.white@ella_white.com', 'ellapass'),
    ('david_smith', 'david.smith@david_smith.com', 'davidpass'),
    ('george_miller', 'george.miller@george_miller.com', 'georgepass'),
    ('sarah_james', 'sarah.james@sarah_james.com', 'sarahpass'),
    ('katherine_smith', 'katherine.smith@katherine_smith.com', 'katherinepass'),
    ('anna_white', 'anna.white@anna_white.com', 'annapass'),
    ('victoria_johnson', 'victoria.johnson@victoria_johnson.com', 'victoriapass'),
    ('hannah_brown', 'hannah.brown@hannah_brown.com', 'hannahpass'),
    ('leonardo_harris', 'leonardo.harris@leonardo_harris.com', 'leonardopass'),
    ('olivia_wilson', 'olivia.wilson@olivia_wilson.com', 'oliviapass'),
    ('evan_scott', 'evan.scott@evan_scott.com', 'evanpass'),
    ('henry_brown', 'henry.brown@henry_brown.com', 'henrypass'),
    ('joseph_white', 'joseph.white@joseph_white.com', 'josephpass'),
    ('maddie_james', 'maddie.james@maddie_james.com', 'maddiepass'),
    ('michael_brown', 'michael.brown@michael_brown.com', 'michaelpass'),
    ('grace_martin', 'grace.martin@grace_martin.com', 'gracepass'),
    ('evan_white', 'evan.white@evan_white.com', 'evanpass')
]